import Router from '@koa/router'
import * as ctrl from '../../controllers/DiTing/kanban'

export const kanbanRoutes = new Router()

kanbanRoutes.get('/api/DiTing/kanban/boards', ctrl.listBoards)
kanbanRoutes.post('/api/DiTing/kanban/boards', ctrl.createBoard)
kanbanRoutes.delete('/api/DiTing/kanban/boards/:slug', ctrl.archiveBoard)
kanbanRoutes.get('/api/DiTing/kanban/capabilities', ctrl.capabilities)
kanbanRoutes.get('/api/DiTing/kanban/stats', ctrl.stats)
kanbanRoutes.get('/api/DiTing/kanban/assignees', ctrl.assignees)
kanbanRoutes.get('/api/DiTing/kanban/diagnostics', ctrl.diagnostics)
kanbanRoutes.post('/api/DiTing/kanban/dispatch', ctrl.dispatch)
kanbanRoutes.get('/api/DiTing/kanban/artifact', ctrl.readArtifact)
kanbanRoutes.get('/api/DiTing/kanban/search-sessions', ctrl.searchSessions)
kanbanRoutes.post('/api/DiTing/kanban/links', ctrl.linkTasks)
kanbanRoutes.delete('/api/DiTing/kanban/links', ctrl.unlinkTasks)
kanbanRoutes.post('/api/DiTing/kanban/tasks/bulk', ctrl.bulkUpdateTasks)
kanbanRoutes.get('/api/DiTing/kanban', ctrl.list)
kanbanRoutes.get('/api/DiTing/kanban/:id', ctrl.get)
kanbanRoutes.post('/api/DiTing/kanban', ctrl.create)
kanbanRoutes.post('/api/DiTing/kanban/complete', ctrl.complete)
kanbanRoutes.post('/api/DiTing/kanban/unblock', ctrl.unblock)
kanbanRoutes.post('/api/DiTing/kanban/:id/block', ctrl.block)
kanbanRoutes.post('/api/DiTing/kanban/:id/assign', ctrl.assign)
kanbanRoutes.post('/api/DiTing/kanban/:id/comments', ctrl.addComment)
kanbanRoutes.get('/api/DiTing/kanban/:id/log', ctrl.taskLog)
kanbanRoutes.post('/api/DiTing/kanban/:id/reclaim', ctrl.reclaim)
kanbanRoutes.post('/api/DiTing/kanban/:id/reassign', ctrl.reassign)
kanbanRoutes.post('/api/DiTing/kanban/:id/specify', ctrl.specify)
