import Router from '@koa/router'
import * as ctrl from '../../controllers/DiTing/sessions'

export const sessionRoutes = new Router()

sessionRoutes.get('/api/DiTing/sessions/conversations', ctrl.listConversations)
sessionRoutes.get('/api/DiTing/sessions/conversations/:id/messages', ctrl.getConversationMessages)
sessionRoutes.get('/api/DiTing/sessions/conversations/:id/messages/paginated', ctrl.getConversationMessagesPaginated)
sessionRoutes.get('/api/DiTing/sessions', ctrl.list)
sessionRoutes.get('/api/DiTing/sessions/count', ctrl.count)
sessionRoutes.get('/api/DiTing/sessions/DiTing', ctrl.listDiTingSessions)
sessionRoutes.get('/api/DiTing/sessions/DiTing/:id', ctrl.getDiTingSession)
sessionRoutes.post('/api/DiTing/sessions/DiTing/:id/import', ctrl.importDiTingSession)
sessionRoutes.get('/api/DiTing/search/sessions', ctrl.search)
sessionRoutes.get('/api/DiTing/sessions/search', ctrl.search)
sessionRoutes.get('/api/DiTing/sessions/usage', ctrl.usageBatch)
sessionRoutes.get('/api/DiTing/usage/stats', ctrl.usageStats)
sessionRoutes.get('/api/DiTing/sessions/context-length', ctrl.contextLength)
sessionRoutes.get('/api/DiTing/sessions/:id/collaboration-runs', ctrl.listCollaborationRuns)
sessionRoutes.get('/api/DiTing/sessions/:id/context', ctrl.getContext)
sessionRoutes.get('/api/DiTing/collaboration-runs/:id', ctrl.getCollaborationRun)
sessionRoutes.get('/api/DiTing/collaboration-runs/:id/events', ctrl.getCollaborationRunEvents)
sessionRoutes.get('/api/DiTing/sessions/:id', ctrl.get)
sessionRoutes.get('/api/DiTing/sessions/:id/export', ctrl.exportSession)
sessionRoutes.get('/api/DiTing/sessions/:id/usage', ctrl.usageSingle)
sessionRoutes.delete('/api/DiTing/sessions/:id', ctrl.remove)
sessionRoutes.post('/api/DiTing/sessions/batch-delete', ctrl.batchRemove)
sessionRoutes.post('/api/DiTing/sessions/:id/rename', ctrl.rename)
sessionRoutes.post('/api/DiTing/sessions/:id/workspace', ctrl.setWorkspace)
sessionRoutes.post('/api/DiTing/sessions/:id/model', ctrl.setModel)
sessionRoutes.get('/api/DiTing/workspace/folders', ctrl.listWorkspaceFolders)
sessionRoutes.post('/api/DiTing/workspace/folders', ctrl.createWorkspaceFolder)
sessionRoutes.post('/api/DiTing/workspace/folders/rename', ctrl.renameWorkspaceFolder)
sessionRoutes.delete('/api/DiTing/workspace/folders', ctrl.deleteWorkspaceFolder)
